# Numpy library: numerical python

NumPy is a popular open-source Python library used for scientific computing and data analysis. 

Its name stands for Numerical Python.

numpy is  a python library using which we can perform different mathematical opearations on arrays 

# import numpy

In [2]:
import numpy as np

In [25]:
# creating a array using a numpy library
x=np.array([1,2,3,4])
print(type(x))
print(x.ndim)
print(x)

<class 'numpy.ndarray'>
1
[1 2 3 4]


In [8]:
# checking the version

np.__version__

'1.26.4'

In [20]:
# 2d array
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x.ndim)
x

2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
#shape
x=np.array([[1,2,3,4],[5,6,7,8]])
x.shape

(2, 4)

In [31]:
#zeros: return a matrix full of zeros
a=np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
a=np.zeros(10)
a.dtype


dtype('float64')

In [40]:
#creating n dimension
x=np.array([1,2,3,4],ndmin=5)
print(x)

[[[[[1 2 3 4]]]]]


In [48]:
x=np.zeros((5,5),dtype=int)
print(x.ndim)
print(x)
print(x.dtype)

2
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int32


In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
np.ones((10,10),dtype=object)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=object)

In [53]:
#full: return a matrix full of any specific number)
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [56]:
#random numbers
np.random.rand()

0.2666180712382633

In [66]:
# return a array of random number bet 0 to 1
x=np.random.rand(10)
print(x)

[0.33245906 0.41089038 0.16126775 0.60877396 0.3215831  0.45650971
 0.65214942 0.72255602 0.97685608 0.16325396]


In [63]:
x=np.random.rand(10)
x

array([0.81280972, 0.60306343, 0.22101706, 0.51370052, 0.03467796,
       0.399346  , 0.63665843, 0.03665719, 0.36392977, 0.42136627])

In [64]:
np.random.rand(10)

array([0.69148063, 0.71106472, 0.55108752, 0.39564864, 0.81644781,
       0.56246452, 0.13419647, 0.85035706, 0.92263281, 0.89593012])

In [69]:
#return a 2d array of random numbers bet 0 to 1
np.random.rand(4,5)

array([[0.40195043, 0.70342245, 0.66936617, 0.98055754, 0.27336191],
       [0.89205152, 0.40218923, 0.76062786, 0.51149922, 0.9032048 ],
       [0.6295844 , 0.21691709, 0.30525102, 0.40004011, 0.34363094],
       [0.57169962, 0.09308994, 0.43110993, 0.18111154, 0.28476486]])

In [74]:
# return a random number bet 1 to 10

np.random.randint(10)

7

In [76]:
import random as rd
x=rd.randint(10,100)
x

16

In [87]:
# return a 2d array between the given interval
np.random.randint(4,100,(3,4))

array([[36, 45, 92, 57],
       [68, 24,  8, 54],
       [72, 95, 44, 54]])

In [6]:
#array slicing[row_slicing,column_slicing]
#row_slicing: var[start:stop+1:step]
#column_slicing: var[start:stop+1:step]
import numpy as np
k=np.random.randint(1,50,(4,4))
k

array([[40, 29, 35, 16],
       [31, 17, 44, 15],
       [ 9,  3, 32, 34],
       [29, 46, 28, 40]])

In [7]:
k[0:3,0:4]

array([[40, 29, 35, 16],
       [31, 17, 44, 15],
       [ 9,  3, 32, 34]])

In [8]:
a[0:3:2,0::3]

array([[ 7, 24],
       [46, 18]])

In [16]:
y=np.random.randint(1,50,(7,7))
y

array([[15, 46,  6, 31, 34,  5, 12],
       [45, 25, 44, 21, 31, 10,  1],
       [42, 40, 19, 42, 14, 22,  4],
       [15, 45, 40,  8, 11, 47,  8],
       [15, 27, 16,  3, 32,  8, 40],
       [43,  6, 45, 36,  2,  4, 49],
       [24, 38, 30, 10, 17,  7, 11]])

In [17]:
y[2:5:2,2:5:2]

array([[19, 14],
       [16, 32]])

In [14]:
r=np.random.randint(1,50,(7,7))
r

array([[49, 27,  8, 37, 48, 36, 45],
       [29, 17, 28, 26, 10, 38, 12],
       [42, 34, 48, 18, 46,  1, 49],
       [16, 37, 20, 10, 27, 13, 20],
       [42, 10,  5, 42, 37, 44, 25],
       [14,  2, 26,  2, 49,  5,  4],
       [10, 42, 37, 42, 25,  4, 12]])

In [15]:
r[0::6,0::6]

array([[49, 45],
       [10, 12]])

# mathematical opearations on numpy

In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([10,11,12,13,14,15,17,18,19])


In [7]:
#addition
np.add(a,b)

array([11, 13, 15, 17, 19, 21, 24, 26, 28])

In [10]:
#subtraction
np.subtract(a,b)

array([ -9,  -9,  -9,  -9,  -9,  -9, -10, -10, -10])

In [8]:
import numpy as np
np.multiply(a,b)

array([ 10,  22,  36,  52,  70,  90, 119, 144, 171])

In [9]:
# divide
np.divide(a,b)

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.41176471, 0.44444444, 0.47368421])

In [11]:
#moduls
np.mod(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# stores quotient and remainder
np.divmod(a,b)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [14]:
#squre root
np.sqrt(a)


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
#power
np.power(a,b)

array([          1,        2048,      531441,    67108864,  1808548329,
        2033549312, -2094633337,           0,  -400556711])

In [16]:
#stastical function
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 17 18 19]


In [19]:
#min
print(np.min(a))
print(np.min(b))

1
10


In [20]:
#max 
print(np.max(a))
print(np.max(b))


9
19


In [21]:
#mean
np.mean(a)

5.0

In [2]:
#where
import numpy as np
a=np.array([1,2,3,4,3,5,6,7,8,9])
np.where(a==3)

(array([2, 4], dtype=int64),)